{% set name = "jsonpath" %}
{% set version = "0.82.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jsonpath-{{ version }}.tar.gz
  sha256: d87ef2bcbcded68ee96bc34c1809b69457ecec9b0c4dd471658a12bd391002d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - jsonpath
  requires:
    - pytest
    - pip
    - python {{ python_min }}
  source_files:
    - test
  commands:
    - pytest test/test1.py test/test2.py test/test3.py
    - pip check

about:
  home: https://pypi.org/project/jsonpath
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A port of the Perl, and JavaScript versions of JSONPath
  doc_url: https://goessner.net/articles/JsonPath/
  dev_url: http://www.ultimate.com/phil/python/#jsonpath

extra:
  recipe-maintainers:
    - hoishing
