{% set name = "jsonpath" %}
{% set version = "0.82.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d87ef2bcbcded68ee96bc34c1809b69457ecec9b0c4dd471658a12bd391002d1

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - jsonpath
  requires:
    - pytest
  source_files:
    - test
  commands:
    - pytest test/test1.py test/test2.py test/test3.py

about:
  home: https://pypi.org/project/jsonpath
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A port of the Perl, and JavaScript versions of JSONPath
  doc_url: https://goessner.net/articles/JsonPath/
  dev_url: http://www.ultimate.com/phil/python/#jsonpath

extra:
  recipe-maintainers:
    - hoishing
